# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCR_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.label.setStyleSheet("border-image: url(:/images/images/背景图片.png);\n"
"border-radius:30px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(269, 50, 141, 51))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 30pt \"华文琥珀\";\n"
"color: rgb(54, 179, 152);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 481, 41))
        self.label_3.setStyleSheet("\n"
"font: 30pt \"华文琥珀\";\n"
"color: rgb(54, 179, 152);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 220, 211, 100))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 20pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 220, 211, 100))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 20pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/237拍照.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(38, 38))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 50, 51, 51))
        self.label_4.setStyleSheet("image: url(:/icons/icons/药品说明书.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(189, 24, 81, 81))
        self.label_5.setStyleSheet("image: url(:/icons/icons/AI.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 121, 121))
        self.label_6.setStyleSheet("image: url(:/icons/icons/花草.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 170, 121, 121))
        self.label_7.setStyleSheet("image: url(:/icons/icons/花草.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 270, 81, 71))
        self.label_8.setStyleSheet("image: url(:/icons/icons/花.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 270, 81, 71))
        self.label_9.setStyleSheet("image: url(:/icons/icons/花.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230, 170, 71, 81))
        self.label_10.setStyleSheet("image: url(:/icons/icons/粮食监管.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(510, 170, 71, 81))
        self.label_11.setStyleSheet("image: url(:/icons/icons/粮食监管.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 10, 30, 41))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"border:none;}\n"
"\n"
"QPushButton:pressed{\n"
"padding-top:5px;}")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minus-circle-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 10, 30, 41))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"border:none;}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"padding-top:5px}\n"
"")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close-circle-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton.raise_()
        self.label_11.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "智问"))
        self.label_3.setText(_translate("MainWindow", "智能药品信息提取播报系统"))
        self.pushButton.setText(_translate("MainWindow", "本地照片识别"))
        self.pushButton_2.setText(_translate("MainWindow", "视频拍照识别"))
import OCR_res_rc
