# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_upload_page(object):
    def setupUi(self, upload_page):
        upload_page.setObjectName("upload_page")
        upload_page.resize(607, 410)
        self.centralwidget = QtWidgets.QWidget(upload_page)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 591, 391))
        self.label.setStyleSheet("border-image: url(:/images/images/背景图片.png);\n"
"border-radius:30px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 10, 30, 41))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"border:none;}\n"
"\n"
"QPushButton:pressed{\n"
"padding-top:5px;}")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus-circle-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 10, 30, 41))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"border:none;}\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"padding-top:5px}\n"
"")
        self.pushButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/close-circle-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 371, 311))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 90, 551, 301))
        self.stackedWidget.setStyleSheet("background-color: transparent;\n"
"\n"
"border-radius: 20px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cam_pic = QtWidgets.QLabel(self.page)
        self.cam_pic.setGeometry(QtCore.QRect(40, 10, 301, 281))
        self.cam_pic.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"color: rgb(54,179,152);\n"
"")
        self.cam_pic.setTextFormat(QtCore.Qt.AutoText)
        self.cam_pic.setScaledContents(False)
        self.cam_pic.setObjectName("cam_pic")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 180, 131, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.shoot_2 = QtWidgets.QPushButton(self.page)
        self.shoot_2.setGeometry(QtCore.QRect(380, 70, 131, 61))
        self.shoot_2.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}")
        self.shoot_2.setObjectName("shoot_2")
        self.pushButton_3.raise_()
        self.shoot_2.raise_()
        self.cam_pic.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.cam_pic_1 = QtWidgets.QLabel(self.page_2)
        self.cam_pic_1.setGeometry(QtCore.QRect(40, 10, 301, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_pic_1.sizePolicy().hasHeightForWidth())
        self.cam_pic_1.setSizePolicy(sizePolicy)
        self.cam_pic_1.setStyleSheet("font: 20pt \"华文琥珀\";\n"
"color: rgb(54,179,152);\n"
"")
        self.cam_pic_1.setObjectName("cam_pic_1")
        self.shoot = QtWidgets.QPushButton(self.page_2)
        self.shoot.setGeometry(QtCore.QRect(134, 240, 131, 61))
        self.shoot.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/237拍照.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shoot.setIcon(icon2)
        self.shoot.setIconSize(QtCore.QSize(34, 34))
        self.shoot.setObjectName("shoot")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(380, 180, 171, 61))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/保存并下一步.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pre_shoot = QtWidgets.QPushButton(self.page_2)
        self.pre_shoot.setGeometry(QtCore.QRect(380, 70, 171, 61))
        self.pre_shoot.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/卡口视频摄像头,监控,桌面摄像头,网络摄像头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pre_shoot.setIcon(icon4)
        self.pre_shoot.setIconSize(QtCore.QSize(40, 40))
        self.pre_shoot.setObjectName("pre_shoot")
        self.pushButton_7.raise_()
        self.pre_shoot.raise_()
        self.cam_pic_1.raise_()
        self.shoot.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 181, 61))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(54, 179, 152);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/文件夹.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 30, 181, 61))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    font: 18pt \"华文琥珀\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    background-color: rgb(54,179,152);}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:rgb(133, 218, 201) ;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(54,179,152);\n"
"}\n"
"")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(215, 30, 81, 41))
        self.label_3.setStyleSheet("image: url(:/images/images/切换.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 10, 51, 51))
        self.label_10.setStyleSheet("image: url(:/icons/icons/粮食监管.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 10, 51, 51))
        self.label_11.setStyleSheet("image: url(:/icons/icons/粮食监管.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 41, 61))
        self.label_6.setStyleSheet("image: url(:/icons/icons/花草.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 0, 41, 61))
        self.label_8.setStyleSheet("image: url(:/icons/icons/花草.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(219, 70, 91, 31))
        self.label_7.setStyleSheet("font: 15pt \"华文琥珀\";\n"
"color: rgb(54,179,152);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.label_2.raise_()
        self.stackedWidget.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.pushButton.raise_()
        self.label_8.raise_()
        self.pushButton_2.raise_()
        self.label_7.raise_()
        upload_page.setCentralWidget(self.centralwidget)

        self.retranslateUi(upload_page)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(upload_page)

    def retranslateUi(self, upload_page):
        _translate = QtCore.QCoreApplication.translate
        upload_page.setWindowTitle(_translate("upload_page", "MainWindow"))
        self.cam_pic.setText(_translate("upload_page", "                照片显示"))
        self.pushButton_3.setText(_translate("upload_page", "下一步"))
        self.shoot_2.setText(_translate("upload_page", "开始上传"))
        self.cam_pic_1.setText(_translate("upload_page", "                照片显示"))
        self.shoot.setText(_translate("upload_page", "拍照"))
        self.pushButton_7.setText(_translate("upload_page", "进入下一步"))
        self.pre_shoot.setText(_translate("upload_page", "打开摄像头"))
        self.pushButton.setText(_translate("upload_page", "本地照片识别"))
        self.pushButton_2.setText(_translate("upload_page", "视频拍照识别"))
        self.label_7.setText(_translate("upload_page", "选择功能"))
import OCR_res_rc
